substitutions:
  board_name: "shelly1v3_boiler"
  board_title: "Shelly Boiler"
  device_num: "01"

esphome:
  name: ${board_name}_${device_num}

esp8266:
  board: esp01_1m
  framework:
    version: 3.0.2

logger:
  level: VERBOSE
  baud_rate: 115200

# Enable Home Assistant API
api:
  reboot_timeout: 900s

socket:
  implementation: meshmesh_esp8266

meshmesh:
  baud_rate: 0
  rx_buffer_size: 0
  tx_buffer_size: 0
  password: !secret meshmesh_password
  channel: 6

switch:
  - platform: gpio
    pin: GPIO4
    id: ${board_name}_${device_num}_relay
    name: "${board_title} ${device_num} Relay"

binary_sensor:                         
  - platform: gpio                     
    pin:                               
      number: GPIO5                    
      #mode: INPUT_PULLUP              
      #inverted: True
    name: "${board_title} ${device_num} Switch"             
    id: ${board_name}_${device_num}_switch


external_components:
  - source:
      type: git
      url: https://github.com/persuader72/esphome-components.git
      ref: master
    components: [ shelly_dallas ]

#external_components:
#  - source: "/home/stefano/Sviluppo/Stefano/Meshmesh/workspace/esphome-components/"

shelly_dallas:
  #pin: GPIO12
  #pin_a: GPIO13
  pin_a: GPIO3
  pin_b: GPIO0

sensor:
  - platform: shelly_dallas
    address: 0xCA011938282E5128
    name: "Temperature #1"
  - platform: shelly_dallas
    address: 0x0B01193807DD3128
    name: "Temperature #2"
#    on_value_range:
#    - above: 58.0
#      then:
#        - switch.turn_off: ${board_name}_${device_num}_relay
#    - below: 50.0
#      then:
#        - switch.turn_on: ${board_name}_${device_num}_relay
  - platform: shelly_dallas
    address: 0x6E0119384DC70728
    name: "Temperature #3"
#  - platform: dallas
#    address: 0xda0416b2082eff28
#    name: "Temperature #3"

